# Generated by Django 4.1.7 on 2023-04-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
    ]
